/**************************************************************************/
/*  godot_app_delegate_service_visionos.mm                                */
/**************************************************************************/
/*                         This file is part of:                          */
/*                             GODOT ENGINE                               */
/*                        https://godotengine.org                         */
/**************************************************************************/
/* Copyright (c) 2014-present Godot Engine contributors (see AUTHORS.md). */
/* Copyright (c) 2007-2014 Juan Linietsky, Ariel Manzur.                  */
/*                                                                        */
/* Permission is hereby granted, free of charge, to any person obtaining  */
/* a copy of this software and associated documentation files (the        */
/* "Software"), to deal in the Software without restriction, including    */
/* without limitation the rights to use, copy, modify, merge, publish,    */
/* distribute, sublicense, and/or sell copies of the Software, and to     */
/* permit persons to whom the Software is furnished to do so, subject to  */
/* the following conditions:                                              */
/*                                                                        */
/* The above copyright notice and this permission notice shall be         */
/* included in all copies or substantial portions of the Software.        */
/*                                                                        */
/* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,        */
/* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF     */
/* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. */
/* IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY   */
/* CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,   */
/* TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE      */
/* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                 */
/**************************************************************************/

#import "godot_app_delegate_service_visionos.h"

#import "godot_compositor_services_renderer.h"

#include "core/config/project_settings.h"
#include "core/os/main_loop.h"
#import "drivers/apple_embedded/os_apple_embedded.h"

// Generated by `setup_swift_builder` (`platform_methods.py`). Exposes `@objc` Swift
// declarations (e.g. `GDTSwiftBridge`) to ObjC++.
#import "godot_swift_module-Swift.gen.h"

static GDTRenderMode _renderMode = GDTRenderModeWindowed;
static __weak cp_layer_renderer_t _layerRenderer = nil;
static __strong cp_layer_renderer_capabilities_t _layerRendererCapabilities = nil;

static bool is_immersive_scene(UIScene *scene) {
	return [scene.session.role isEqualToString:UISceneSessionRoleImmersiveSpaceApplication] ||
			[scene.session.role isEqualToString:@"CPSceneSessionRoleImmersiveSpaceApplication"];
}

@implementation GDTAppDelegateServiceVisionOS {
	BOOL _immersiveSceneInBackground;
}

- (void)notifyEngineEnteredBackground {
	// Give the queued pause notification a finite opportunity before suspension.
	__block UIBackgroundTaskIdentifier task = UIBackgroundTaskInvalid;
	void (^end_task)(void) = ^{
		if (task != UIBackgroundTaskInvalid) {
			[UIApplication.sharedApplication endBackgroundTask:task];
			task = UIBackgroundTaskInvalid;
		}
	};
	task = [UIApplication.sharedApplication beginBackgroundTaskWithName:@"Godot pause notification" expirationHandler:end_task];
	visionos_dispatch_to_engine(^{
		OS_AppleEmbedded::get_singleton()->on_enter_background();
		dispatch_async(dispatch_get_main_queue(), end_task);
	});
}

+ (BOOL)hasImmersiveScene {
	for (UIScene *scene in UIApplication.sharedApplication.connectedScenes) {
		if (is_immersive_scene(scene) && scene.activationState != UISceneActivationStateUnattached) {
			return YES;
		}
	}
	return NO;
}

+ (GDTRenderMode)renderMode {
	return _renderMode;
}

+ (void)setRenderMode:(GDTRenderMode)renderMode {
	_renderMode = renderMode;
}

+ (cp_layer_renderer_t)layerRenderer {
	if (_renderMode != GDTRenderModeCompositorServices) {
		NSLog(@"GDTAppDelegate error, layerRenderer only supported in Compositor Services mode");
		return nil;
	}
	@synchronized(self) {
		return _layerRenderer;
	}
}

+ (void)setLayerRenderer:(cp_layer_renderer_t)layerRenderer {
	if (_renderMode != GDTRenderModeCompositorServices) {
		NSLog(@"GDTAppDelegate error, layerRenderer only supported in Compositor Services mode");
		return;
	}
	@synchronized(self) {
		_layerRenderer = layerRenderer;
	}
}

+ (cp_layer_renderer_capabilities_t)layerRendererCapabilities {
	if (_renderMode != GDTRenderModeCompositorServices) {
		NSLog(@"GDTAppDelegate error, layerRenderer only supported in Compositor Services mode");
		return nil;
	}
	@synchronized(self) {
		return _layerRendererCapabilities;
	}
}

+ (void)setLayerRendererCapabilities:(cp_layer_renderer_capabilities_t)layerRendererCapabilities {
	if (_renderMode != GDTRenderModeCompositorServices) {
		NSLog(@"GDTAppDelegate error, layerRenderer only supported in Compositor Services mode");
		return;
	}
	@synchronized(self) {
		_layerRendererCapabilities = layerRendererCapabilities;
	}
}

+ (BOOL)isDynamicRenderQualityEnabled {
	return GLOBAL_GET("xr/visionos/dynamic_render_quality/enable");
}

+ (float)maxRenderQuality {
	return GLOBAL_GET("xr/visionos/dynamic_render_quality/maximum_quality");
}

+ (GDTVisibility)initialUpperLimbVisibility {
	return (GDTVisibility)(int)GLOBAL_GET("xr/visionos/upper_limb_visibility");
}

+ (GDTVisibility)initialPersistentSystemOverlays {
	return (GDTVisibility)(int)GLOBAL_GET("xr/visionos/persistent_system_overlays");
}

// `immersionStyle`, `upperLimbVisibility` and `persistentSystemOverlays` are stored on the
// SwiftUI `Model`; these accessors forward through `GDTSwiftBridge`, which does the
// SwiftUI<->ObjC conversion.

+ (GDTImmersionStyle)immersionStyle {
	__block GDTImmersionStyle value;
	safeDispatchSyncToMain(^{
		value = GDTSwiftBridge.immersionStyle;
	});
	return value;
}

+ (void)setImmersionStyle:(GDTImmersionStyle)immersionStyle {
	safeDispatchSyncToMain(^{
		GDTSwiftBridge.immersionStyle = immersionStyle;
	});
}

+ (GDTVisibility)upperLimbVisibility {
	__block GDTVisibility value;
	safeDispatchSyncToMain(^{
		value = GDTSwiftBridge.upperLimbVisibility;
	});
	return value;
}

+ (void)setUpperLimbVisibility:(GDTVisibility)upperLimbVisibility {
	safeDispatchSyncToMain(^{
		GDTSwiftBridge.upperLimbVisibility = upperLimbVisibility;
	});
}

+ (GDTVisibility)persistentSystemOverlays {
	__block GDTVisibility value;
	safeDispatchSyncToMain(^{
		value = GDTSwiftBridge.persistentSystemOverlays;
	});
	return value;
}

+ (void)setPersistentSystemOverlays:(GDTVisibility)persistentSystemOverlays {
	safeDispatchSyncToMain(^{
		GDTSwiftBridge.persistentSystemOverlays = persistentSystemOverlays;
	});
}

- (void)sceneDidBecomeActive:(UIScene *)scene API_AVAILABLE(ios(13.0), tvos(13.0), visionos(1.0)) {
	if (_renderMode != GDTRenderModeCompositorServices) {
		[super sceneDidBecomeActive:scene];
		return;
	}
	if (!is_immersive_scene(scene)) {
		return;
	}
	BOOL was_backgrounded = _immersiveSceneInBackground;
	_immersiveSceneInBackground = NO;
	visionos_dispatch_to_engine(^{
		if (was_backgrounded) {
			OS_AppleEmbedded::get_singleton()->on_exit_background();
		}
		OS_AppleEmbedded::get_singleton()->on_focus_in();
	});

	// On Compositor Services scenes, sceneDidBecomeActive: is called too soon when
	// donning the device, which attempts to start the audio driver too early. Start it
	// again after a short delay so audio resumes correctly.
	dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.5 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
		if (scene.activationState == UISceneActivationStateForegroundActive) {
			visionos_dispatch_to_engine(^{
				OS_AppleEmbedded::get_singleton()->audio_driver_start();
			});
		}
	});
}

// Auxiliary launcher windows do not own the immersive engine's focus or pause state.
// Immersive scene and application callbacks still handle genuine backgrounding.
- (void)sceneDidDisconnect:(UIScene *)scene {
	if (_renderMode == GDTRenderModeCompositorServices) {
		if (is_immersive_scene(scene)) {
			visionos_dispatch_to_engine(^{
				OS_AppleEmbedded::get_singleton()->on_focus_out();
			});
		}
		return;
	}
	[super sceneDidDisconnect:scene];
}

- (void)sceneWillEnterForeground:(UIScene *)scene {
	if (_renderMode == GDTRenderModeCompositorServices) {
		if (is_immersive_scene(scene)) {
			visionos_dispatch_to_engine(^{
				OS_AppleEmbedded::get_singleton()->on_exit_background();
			});
		}
		return;
	}
	[super sceneWillEnterForeground:scene];
}

- (void)sceneWillResignActive:(UIScene *)scene {
	if (_renderMode == GDTRenderModeCompositorServices) {
		if (is_immersive_scene(scene)) {
			visionos_dispatch_to_engine(^{
				OS_AppleEmbedded::get_singleton()->on_focus_out();
			});
		}
		return;
	}
	[super sceneWillResignActive:scene];
}

- (void)sceneDidEnterBackground:(UIScene *)scene {
	if (_renderMode == GDTRenderModeCompositorServices) {
		if (is_immersive_scene(scene)) {
			_immersiveSceneInBackground = YES;
			[self notifyEngineEnteredBackground];
		}
		return;
	}
	[super sceneDidEnterBackground:scene];
}

- (void)applicationWillEnterForeground:(UIApplication *)application {
	if (_renderMode == GDTRenderModeCompositorServices) {
		visionos_dispatch_to_engine(^{
			OS_AppleEmbedded::get_singleton()->on_exit_background();
		});
		return;
	}
	[super applicationWillEnterForeground:application];
}

- (void)applicationDidBecomeActive:(UIApplication *)application {
	if (_renderMode == GDTRenderModeCompositorServices) {
		visionos_dispatch_to_engine(^{
			OS_AppleEmbedded::get_singleton()->on_focus_in();
		});
		return;
	}
	[super applicationDidBecomeActive:application];
}

- (void)applicationWillResignActive:(UIApplication *)application {
	if (_renderMode == GDTRenderModeCompositorServices) {
		visionos_dispatch_to_engine(^{
			OS_AppleEmbedded::get_singleton()->on_focus_out();
		});
		return;
	}
	[super applicationWillResignActive:application];
}

- (void)applicationDidEnterBackground:(UIApplication *)application {
	if (_renderMode == GDTRenderModeCompositorServices) {
		[self notifyEngineEnteredBackground];
		return;
	}
	[super applicationDidEnterBackground:application];
}

- (void)applicationDidReceiveMemoryWarning:(UIApplication *)application {
	if (_renderMode == GDTRenderModeCompositorServices) {
		visionos_dispatch_to_engine(^{
			if (OS::get_singleton()->get_main_loop()) {
				OS::get_singleton()->get_main_loop()->notification(MainLoop::NOTIFICATION_OS_MEMORY_WARNING);
			}
		});
		return;
	}
	[super applicationDidReceiveMemoryWarning:application];
}

- (void)onAudioInterruption:(NSNotification *)notification {
	if (_renderMode == GDTRenderModeCompositorServices) {
		visionos_dispatch_to_engine(^{
			[super onAudioInterruption:notification];
		});
		return;
	}
	[super onAudioInterruption:notification];
}

- (void)applicationWillTerminate:(UIApplication *)application {
	if (_renderMode == GDTRenderModeCompositorServices) {
		// Termination is best-effort on UIKit. Never join an owner that may need
		// a main-actor UI call; persistence belongs to the earlier pause event.
		visionos_finish_engine();
		return;
	}
	[super applicationWillTerminate:application];
}

@end
